import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
export const metadata: Metadata = { title: "Exclusão de conta", description: "Solicite a exclusão da sua conta e dos dados associados ao Layvo Gestão." };
const sections = [
  {title:"Como solicitar a exclusão",paragraphs:["Envie uma mensagem a partir do e-mail cadastrado no Layvo para contato@layvo.com.br, com o assunto “Exclusão de conta”. Informe o nome da empresa vinculada à conta para facilitar a identificação.","Confirmaremos o recebimento e poderemos solicitar uma verificação de identidade antes de concluir a exclusão, para proteger sua conta contra solicitações indevidas."]},
  {title:"O que será excluído",paragraphs:["Após a validação, excluiremos ou anonimizaremos os dados da conta, o vínculo com a empresa, os registros de dispositivos e os feedbacks associados, ressalvadas as informações cuja conservação seja necessária para cumprir obrigação legal, prevenir fraude ou resguardar direitos.","Você receberá uma confirmação no e-mail cadastrado quando o processo for concluído."]},
  {title:"Dados que ficam no seu aparelho",paragraphs:["Clientes, fornecedores, produtos, estoque, vendas, compras, crediário, financeiro e outros dados operacionais são armazenados localmente. Para removê-los, apague os dados do aplicativo ou desinstale o Layvo Gestão do aparelho.","Faça essa remoção somente depois de exportar o que deseja conservar. A exclusão da conta online não remove automaticamente o banco local."]},
  {title:"Backups e serviços externos",paragraphs:["Arquivos de backup, comprovantes e relatórios enviados para Google Drive, mensageiros ou outros destinos permanecem sob seu controle. Exclua esses arquivos diretamente nos serviços onde foram salvos.","A Layvo não recebe a senha dos backups criptografados e não consegue acessar ou apagar arquivos mantidos em serviços externos."]},
  {title:"Prazo e dúvidas",paragraphs:["A solicitação será atendida em prazo razoável, observados os requisitos de segurança e os prazos previstos na legislação aplicável.","Se você apenas deseja corrigir dados ou esclarecer uma dúvida de privacidade, use o mesmo canal de contato sem solicitar o encerramento da conta."]},
];
export default function Page(){return <LegalPage title="Exclusão de conta" intro="Aqui você encontra o passo a passo para excluir sua conta Layvo e entender o que acontece com os dados." sections={sections}/>;}
